Sprint 7 solution in file manager
AlexanderMarkin27/java-kanban pull request #3
Opened 2024-03-21 21:15 UTC by AlexanderMarkin27

2024-03-26 16:02 UTC, TomattmanYandex requested changes
Привет, комменты в коде

2024-03-26 16:02 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/TaskManager.java
> +    void createTask(Task task);
предыдущая версия была лучше, в ней можно было на возвращаемое значение завязаться чтобы понять все ли прошло успешно

2024-03-26 16:02 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/TaskManager.java
> +    void createTask(Task task);
а для работы новых методов в файловом менеджере
1) выполнили метод из родительского класса
2) записали результат в переменную
3) вызвали метод сохранения
4) вернули значение из переменной

2024-06-08 07:50 UTC, TomattmanYandex requested changes
Привет, еще есть моменты на исправление

2024-06-08 07:50 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +    public void loadFromFile() throws IOException {
этот метод должен быть приватным

2024-06-08 07:50 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +    public void loadFromFile() throws IOException {
и по условию, ты должен ловить IOException и пробрасывать свое, непроверяемое исключение

2024-06-08 07:50 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +            epicArrayList.forEach(this::createEpic);
эпики будут без списка сабтасков, надо пройтись по списку сабтасков, и каждому из их эпиков, добавить идентификатор сабтаска в список сабтасков
Второй момент, тут нельзя использовать методы createEpic, createTask, createSubtask, потомуб что они устанавливают новый идентификатор, и тогда потеряется связь между сабтасками и эпиками
здесь стоит  добавлять их в мапы напрямую, методом put
Третий момент, в начале стоит добавить эпики, а потом при добавлении сабтасков, можно как раз добавлять их эпикам
Четвертое - после всех этих действий, счетчик для идентификаторов не поменяется, но его надо поменять, чтобы не было пересечений в существующих значениях и в новых

2024-06-08 07:50 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +            e.printStackTrace();
вот тут по условию должно просбрасываться свое исключение

2024-06-08 07:50 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +    public static FileBackedTaskManager getInstance(File file, HistoryManager historyManager) throws IOException {
кажется по условию этот метод должен иметь другое имя

2024-06-08 07:50 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +            epicArrayList.forEach(this::createEpic);
p.s. для того чтобы было доступ к мапам, надо сделать их protected

2024-06-09 19:13 UTC, AlexanderMarkin27 commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +    public static FileBackedTaskManager getInstance(File file, HistoryManager historyManager) throws IOException {
Ничего не нашел в условии по поводу имени. Я был в академе, может у меня что-то не обновилось)

2024-06-10 11:05 UTC, TomattmanYandex approved these changes
Принято

2024-06-10 11:05 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +    public static FileBackedTaskManager getInstance(File file, HistoryManager historyManager) throws IOException {
Кроме метода сохранения, создайте статический метод static FileBackedTaskManager loadFromFile(File file), который будет восстанавливать данные менеджера из файла при запуске программы.

Скопировал из задания

2024-06-10 11:05 UTC, TomattmanYandex commented on src/com/yandex/taskTracker/service/FileBackedTaskManager.java
> +    public static FileBackedTaskManager getInstance(File file, HistoryManager historyManager) throws IOException {
но это мелочи

2024-06-10 19:02 UTC, merged